config/routes.rb
Rails.application.routes.draw do
  root 'user_sessions#new'

  resources :courses, only: [:new, :create, :show, :edit, :update, :destroy, :index], shallow: true do
    resources :rosters, only:[:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  resources :users, only: [:show, :edit, :update, :destroy, :new, :create] do
    member do
      get :activate
      patch :confirm
    end
  end

  resources :rosters do
    member do
      get :export
    end
  end

  resources :evals, shallow: true do
    resources :categories, only: [:new, :create, :edit, :update, :destroy], shallow: true do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :students, only: [:show] do
    resources :grades, only: [:new, :create, :show, :edit, :update ]
  end

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :course
  has_one :professor, through: :course
  has_many :evals, through: :course
  has_and_belongs_to_many :students
  has_many :grades, through: :students
  accepts_nested_attributes_for :students

  def as_csv
    students = Student.where('roster_id = ?', id)
    excluded_names = ['id', 'created_at', 'updated_at', 'roster_id']
    column_names = (Student.column_names - excluded_names)
    self.evals.order(title: :asc).each {|eval| column_names << eval.title }
    CSV.generate do |csv|
      csv << column_names
      students.each do |student|
        attributes = student.attributes.values_at(*(Student.column_names - excluded_names))
        student.grades.order(title: :asc).each {|grade| attributes << (grade.final_score.nil? ? "NA" : grade.final_score.to_f/100)}
        csv << attributes
      end
    end
  end
# Determines the average score for a particular section of a class
  def average_score
    score_total = self.grades.reduce(0) {|sum, grade| sum += grade.final_score.to_f; sum}

    unless score_total == 0
      (score_total / self.students.count) / 100
    end
  end
#Determines the average score on a particular eval
  def average_eval_score(eval)
    grades = self.grades.where("eval_id = ?", eval.id)
    if grades.empty?
      "No grades for this eval yet"
    else
      (grades.reduce(0) {|sum, grade| sum += grade.final_score.to_i; sum} / grades.count).to_f / 100
    end
  end
#Returns an array of grades on a particular eval for each student within a roster
  def eval_grades(eval)
    eval_grades = Grades.where("eval_id = ?", eval.id)
    desc_scores = []
    eval_grades.each do |grade|
      desc_scores << grade.final_score.to_f
    end
    desc_scores.sort! {|x,y| y <=> x }
  end
#Returns a collection of a roster's scores and sorts them from lowest to highest
  def roster_descending_scores
    roster_scores_array = []
    self.students.each do |student|
      roster_scores_array << (student.total_score.to_f / 100)
    end
    roster_scores_array.sort! {|x,y| y <=> x }
  end
#Determines a max score that this particlar section is out of
  def roster_max_score
    self.evals.reduce(0) {|sum, eval| sum + eval.max_score.to_f; sum }
  end
#Determines the percent of the course is complete for that
#particular section based on the number of grade objects
#for a course and the total number possible

  def percent_complete
    #Total the possible grade objects
    possible_grades = self.evals.count * self.students.count
    #Divide number of grades currently by possible_grades to get percentage
    # Times one hundred to format for jQuery Knob
    if self.grades.count == 0
      0
    else
      ((self.grades.count.to_f / possible_grades) * 100).to_i
    end
  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :load_course, only: [:new, :create]

  def index
    @rosters = if params[:selected]
      case params[:selected]
      when "active"
        current_user.active_rosters
      when "recent"
        current_user.recent_rosters
      when "upcoming"
        current_user.upcoming_rosters
      end
    else
      current_user.active_rosters
    end


    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @roster = @course.rosters.build
    student = @roster.students.build
  end

  def create
    @roster = @course.rosters.build(roster_params.except(:start_date, :end_date, :students_attributes))

    @roster.start_date = Time.strptime(params[:roster][:start_date], "%m/%d/%Y")
    @roster.end_date = Time.strptime(params[:roster][:end_date], "%m/%d/%Y")

    if @roster.save
      Student.import(roster_params[:students_attributes]["0"], @roster)
      redirect_to course_path(@roster.course.id)
    else
      flash.now[:alert] = "Your roster was not saved..."
      render :new
    end
  end

  def show
    @roster = Roster.find(params[:id])
  end

  def edit
    @roster = Roster.find(params[:id])
  end

  def update
    @roster = Roster.find(params[:id])

    if @roster.update(roster_params)
      redirect_to @roster, notice: "Changes to #{@roster.section_name} were saved!"
    else
      flash.now[:alert] = "Your changes were not saved..."
      render :edit
    end
  end

  def destroy
    @roster = Roster.find(params[:id])
    @roster.destroy
    redirect_to current_user
  end

  def export
    @roster = Roster.find(params[:id])
    send_data @roster.as_csv, type: "text/csv", filename: "#{@roster.section_name}.csv"
  end

      private
  def roster_params
    params.require(:roster).permit(:section_name, :meet_time, :location, :meet_day, :course_id, students_attributes: [:file])
  end

  def load_course
    @course = Course.find(params[:course_id])
  end
end

app/helpers/rosters_helper.rb
module RostersHelper
  def days_of_week
    return [["Monday", "Monday"],["Tuesday", "Tuesday"], ["Wednesday", "Wednesday"], ["Thursday", "Tuesday"], ["Friday", "Friday"]]
  end

  def time_slots
   return (1..24).to_a
  end

  def link_or_grade(student, eval_id)
    container = student.grades.where("eval_id = ?", eval_id)
    if container[0]
      link_to format_score(container[0].final_score), edit_student_grade_path(student, container[0])
    else
      link_to "Grade", new_student_grade_path(student, eval_id: eval_id)
    end
  end
end

app/views/rosters/_roster.html.haml
.info-card
  =link_to roster_path(roster.id) do
    .info-card-header
      #{roster.course.name}
    .info-card-body
      %strong Section:
      = roster.section_name
    .info-card-body
      #{roster.start_date.strftime('%a %b %d, %Y')} - #{roster.end_date.strftime('%a %b %d, %Y')}
    .info-card-knob
      = tag 'input', type: "text", class: 'dial', id:"avg-#{roster_counter}", data: { max: (roster.course.possible_points / 100)}, value: "#{roster.average_score}"
      %p Average Score
    .info-card-knob
      = tag 'input', type: "text", class: 'dial', id: "progress-#{roster_counter}", value: "#{roster.percent_complete}"
      %p % Complete
    .btn-container
      = link_to "Remove", roster_path(roster.id), class: "btn btn-delete", confirm: "Are you sure you would like to permenantly delete #{roster.section_name}?", method: :delete

app/views/rosters/_roster_errors.html.haml
.error-messages
  %h4
    =pluralize(@roster.errors.count, "error")
    prohibited this roster from saving:

  %ul
    -errors.full_messages.each do |msg|
    %li= msg

app/views/rosters/_roster_form.html.haml
-if @roster.errors.any?
  = render 'roster_errors'
=form_for [@course, @roster] do |f|
  .user-input
    = f.label :section_name, "Section Name:"
    = f.text_field :section_name
  .user-input
    =f.label :start_date, "Start Date:"
    =f.text_field :start_date, class: "datepicker"
  .user-input
    =f.label :start_date, "End Date:"
    =f.text_field :end_date, class: "datepicker"
  .user-input
    =f.label :meet_day, "Day:"
    =f.select :meet_day, days_of_week
  .user-input
    =f.label :meet_time, "Time:"
    =f.select :meet_time, time_slots
  .user-input
    =f.label :location, "Location:"
    =f.text_field :location

    =f.fields_for :students do |ff|
      .upload-btn
        =ff.label :file, "Import a CSV:"
        =ff.file_field :file
  .submit-btn
    =f.button

app/views/rosters/edit.html.haml
%h1
  Edit
  =@roster.section_name
=render 'roster_form'

app/views/rosters/index.js.erb
$('#roster-index').html("<%= j(render  @rosters) %>");

app/views/rosters/new.html.haml
.form
  %h1 Create a new Roster!
  = render 'roster_form'

app/views/rosters/show.html.haml
.new
  %h1= @roster.section_name
  %ul
    %li
      %strong Meet Time:
      =@roster.meet_day
      at
      =@roster.meet_time
    %li
      %strong Location:
      =@roster.location

  = link_to "Export Roster", export_roster_path

/Roster table
%h3 Students
.scrolling-table
  %table.table-minimalxyz
    %thead
      %tr
        %th Name
        %th Email Address
        %th Uid
        - @roster.evals.each do |eval|
          %th= link_to "#{eval.title}", eval_path(eval)
        %th Total Score


    %tbody
      -@roster.students.each do |student|
        %tr
          %td= first_last(student)
          %td= student.email
          %td= student.uid
          -student.evals(@roster.id).each do |eval|
            %td= link_or_grade(student, eval.id)
          %td= format_score(student.total_score)
/Evals accordion
%h3 Evaluations
%ul.accordion-tabs
  -@roster.evals.each do |eval|
    %li.tab-header-and-content
      =link_to eval.title, "#", class: "is-active tab-link"
      .tab-content
        %p= @roster.average_eval_score(eval)