config/routes.rb
Rails.application.routes.draw do
  root 'user_sessions#new'

  resources :courses, only: [:new, :create, :show, :edit, :update, :destroy, :index], shallow: true do
    resources :rosters, only:[:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  resources :users, only: [:show, :edit, :update, :destroy, :new, :create] do
    member do
      get :activate
      patch :confirm
    end
  end

  resources :rosters do
    member do
      get :export
    end
  end

  resources :evals, shallow: true do
    resources :categories, only: [:new, :create, :edit, :update, :destroy], shallow: true do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :students, only: [:show] do
    resources :grades, only: [:new, :create, :show, :edit, :update ]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :grades
  authenticates_with_sorcery!
  attr_accessor :remove_avatar
  TYPES = %i[professor assistant]
  # has_secure_password
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name,  presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, confirmation:true, on: :create
  validates :password_confirmation, presence: true, on: :create
  has_attached_file :avatar, styles: { :medium => "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type:/\Aimage\/.*\Z/
  before_save :delete_avatar, if: ->{ remove_avatar == '1' && !avatar_updated_at_changed? }
  #Allows user to be created without until activated password using sorcery gem
  before_save { self.email.downcase! }
  before_create :setup_activation
  #Sorcery method to set external auth (Oauth) to false
  def external?
    false
  end
#Checks how many grades you have created in the last 3 days
  def grades_last_three
    self.grades.where("created_at > ?", (Time.now - 3.day)).count
  end
#Scope that returns currently active rosters on a per user basis
  def active_rosters
    date = Time.now
    self.rosters.includes(:course).where(('start_date <= ? AND end_date >= ?'), date, date)
  end

  def upcoming_rosters
    date = Time.now
    self.rosters.includes(:course).where(('start_date > ?'), date)
  end

  def recent_rosters
    date = Time.now
    self.rosters.includes(:course).where(('end_date < ? AND end_date < end_date + ?'), date, 31.day)
  end

  private
  def delete_avatar
    self.avatar = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:create, :activate, :confirm]

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @token = params[:id]
    else
      not_authenticated
    end
  end

  def confirm
    @token = params[:user][:token]
    if @user = User.load_from_activation_token(@token)
      if @user.update_attributes(user_params)
        @user.activate!
        auto_login @user
        redirect_to @user, notice: "#{@user.first_name} was activated successfully!"
      else
        render :activate
      end
    else
      not_authenticated
    end
  end

  def new
    @assistant = Assistant.new
    course_id = params[:course_id]
  end

  def create
    @assistant = Assistant.new(user_params)

    if @assistant.save
      redirect_to user_path(current_user), notice:"Email to #{@assistant.first_name} has been sent!"
    else
      flash.now[:alert] = "Email was not sent..."
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(params[:id])
    @active_rosters = @user.active_rosters.limit(6)

    @rosters = current_user.active_rosters



    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Your changes were saved!"
    else
      flash.now[:alert] = "Your changes were not saved..."
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :course_ids, :email, :password, :avatar, :remove_avatar, :activation_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_confirm_user_form.html.haml
=form_for @user, url: confirm_user_url(@user) do |f|
  .user-input
    = f.label :first_name, "First Name:"
    = f.text_field :first_name
  .user-input
    = f.label :last_name, "Last Name:"
    = f.text_field :last_name
  .user-input
    = f.label :password, "Password Minimum of Six Characters:"
    = f.password_field :password
  .user-input
    = f.label :password_confirmation, "Password Minimum of Six Characters:"
    = f.password_field :password_confirmation
    = f.hidden_field :token, value: @token
  .submit-button
    = f.button

app/views/users/_course_chart.html.haml
= link_to course_path(course) do
  = content_tag 'div', class: "course-chart", id:"chart#{index}", data: { student_points: course.scores }, style:"width:100%; height:300px; font-size:11px; position: relative; margin-top: -30px" do
    Loading course charts...

app/views/users/_user_form.html.haml
=form_for @user, :url => user_path, :html => { :multipart => true } do |f|
  .user-input.name
    = f.label :first_name, "First Name:"
    = f.text_field :first_name
  .user-input.name
    = f.label :last_name, "Last Name:"
    = f.text_field :last_name
  %br
  %br
  %br
  %br
  .user-input
    = f.label :avatar
    = f.file_field :avatar
  %p
    - if @user.avatar?
      = image_tag @user.avatar.url(:thumb)
      = f.label :remove_avatar
      = f.check_box :remove_avatar
  .user-input
    = f.label :email, "Email Address:"
    = f.text_field :email
  .submit-button
    = f.button

app/views/users/_user_invite.html.haml
=form_for @assistant do |f|
  =f.hidden_field :course_ids, value: params[:course_ids]
  .user-input
    = f.label :first_name, "First Name:"
    = f.text_field :first_name
  .user-input
    = f.label :last_name, "Last Name:"
    = f.text_field :last_name
  .user-input
    = f.label :email, "Email Address:"
    = f.text_field :email
  .submit-button
    = f.button "Send Invite"

app/views/users/activate.html.haml
%h1 Activate your account!
= render 'confirm_user_form'

app/views/users/edit.html.haml
.login
  %h1 Settings
  = render 'user_form'
  / %h1 Request Password Reset
  / = render 'password_resets/_request_email_form.html.haml'

app/views/users/new.html.haml
.login
  %h1 Invite a TA!
  = render 'user_invite'

app/views/users/show.html.haml
.avatar-main-container
  - if @user.avatar?
    = image_tag @user.avatar.url(:medium), class: "avatar-frame"
  .avatar-name-container
    %br
    %h2 #{@user.first_name} #{@user.last_name}
    %h5 #{@user.type}
    %h6= link_to "Edit My Account", edit_user_path
  .exit-container-plus
    = link_to new_eval_path do
      %i.icon-plus.tooltip-item
        .tooltip
          Create Evaluation
%br
%h1 Current Courses
- if @user.type == "Professor" && @active_rosters.empty?
  %p
    %i You do not appear to have any courses at the moment. How nice. #{link_to "Start here!", new_course_path }
- else
  .vertical-tabs-container
    .vertical-tabs
      - @active_rosters.each.with_index do |roster, index|
        - if index == 0
          =link_to roster.course.name, "#", class: "js-vertical-tab vertical-tab is-active", rel: "tab#{index}", data: { index: "#{index}"}
        - else
          =link_to roster.course.name, "#", class: "js-vertical-tab vertical-tab", rel: "tab#{index}", data: { index: "#{index}"}
    .vertical-tab-content-container
      - @active_rosters.each.with_index do |roster, index|
        - if index == 0
          =link_to roster.course.name, "#", class: "js-vertical-tab-accordion-heading vertical-tab-accordion-heading is-active", rel: "tab#{index}"
          .js-vertical-tab-content.vertical-tab-content{id: "tab#{index}"}
            = render partial: 'course_chart', locals: {course: roster.course, index: index}
        - else
          =link_to roster.course.name, "#", class: "js-vertical-tab-accordion-heading vertical-tab-accordion-heading", rel: "tab#{index}"
          .js-vertical-tab-content.vertical-tab-content{id: "tab#{index}"}
            = render partial: 'course_chart', locals: {course: roster.course, index: index}
.title-box
  %h1 Sections
  .roster-nav
    %ul
      %li
        = link_to "Active", "#", class: "roster-links", id: "active"
      %span //
      %li
        = link_to "Recent", "#", class: "roster-links", id: "recent"
      %span //
      %li
        = link_to "Upcoming", "#", class: "roster-links", id: "upcoming"
.user-roster-cards#roster-index
  = render @rosters

app/views/users/show.js.erb
$('#roster-index').html("<%= j(render  @rosters) %>");