config/routes.rb
Rails.application.routes.draw do
  root 'user_sessions#new'

  resources :courses, only: [:new, :create, :show, :edit, :update, :destroy, :index], shallow: true do
    resources :rosters, only:[:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  resources :users, only: [:show, :edit, :update, :destroy, :new, :create] do
    member do
      get :activate
      patch :confirm
    end
  end

  resources :rosters do
    member do
      get :export
    end
  end

  resources :evals, shallow: true do
    resources :categories, only: [:new, :create, :edit, :update, :destroy], shallow: true do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :students, only: [:show] do
    resources :grades, only: [:new, :create, :show, :edit, :update ]
  end

end

app/models/eval.rb
class Eval < ActiveRecord::Base
  has_many :categories
  has_many :comments, :through => :categories
  belongs_to :professor
  has_and_belongs_to_many :courses
  accepts_nested_attributes_for :categories, :allow_destroy => true
  before_save :total

  def total
    self.max_score = (self.categories.reduce(0) {|sum, category| sum += (category.max_score.to_f / 100); sum }.to_i * 100).to_s
  end
end

app/controllers/evals_controller.rb
class EvalsController < ApplicationController
  # load_and_authorize_resource

  #do we need this?
  def index

  end
  #do we need this?
  def show
    @eval = Eval.find(params[:id])
  end

  def new
    @eval = Eval.new
    @category = @eval.categories.build
    @comment = @category.comments.build
  end

  def create
    @eval = Eval.new(eval_params)
    @eval.professor = current_user
    if @eval.save
      redirect_to evals_url
    else
      render :new
    end
  end

  def edit
    @eval = Eval.find(params[:id])
  end

  def update
    @eval = Eval.find(params[:id])

    if @eval.update(eval_params)
      redirect_to eval_path(@eval)
    else
      render :edit
    end
  end

  def destroy
    @eval = Eval.find(params[:id])
    @eval.destroy
    redirect_to evals_url
  end

private
  def eval_params
    params.require(:eval).permit(:title, :template, :course_ids, categories_attributes: [:title, :max_score, :id, :_destroy, comments_attributes: [:description, :id, :_destroy]])
  end
end

app/helpers/evals_helper.rb
module EvalsHelper
end

app/views/evals/_category_fields.html.haml
.nested-fields
  %ul
    .field.title
      = f.label :category
      = f.text_field :title, :placeholder => "Add a category..."
    .field.score
      = f.label :score
      - if f.object.max_score
        = f.number_field :max_score, step: "any", :value =>format_score(f.object.max_score)
      - else
        = f.number_field :max_score, step: "any", :placeholder => 100
    = link_to_remove_association " ", f, class: "icon-minus"
  #masks.bottom
    = f.fields_for :comments do |comment|
      .comment-container
        = render 'comment_fields', :f => comment
    .links.bottom#argh
      = link_to_add_association "+ Add a Comment", f, :comments

app/views/evals/_category_form.html.haml
= form_for [@eval, @category] do |f|

  = f.label :title
  = f.text_field :title
  %br
  = f.label :score
  = f.number_field :score
  %br
  = f.submit "Save"

app/views/evals/_comment_fields.html.haml
.field
  .nested-fields
    .field.comment
      = f.text_field :description, :placeholder => "Add a comment..."
    =link_to_remove_association " ", f, class: "icon-minus"

app/views/evals/_form.html.haml
.fields
= form_for @eval do |f|
  .field.title
    = f.label :title
    = f.text_field :title, :placeholder => "Add a title..."
  .field.template
    = f.label :template
    = f.select :template, [['Rubric', 'rubric'], ['Scheme', 'scheme']]
  .field.template
    = f.label :course
    = f.select :course_ids, options_from_collection_for_select(current_user.courses, :id, :name)
  %br
  .links
    = link_to_add_association '+ Add a Category', f, :categories, { :"data-association-insertion-node" => '#tasks', :"data-association-insertion-method" => 'append' }
  #tasks
    = f.fields_for :categories do |category|
      = render 'category_fields', :f => category
  = f.submit

app/views/evals/edit.html.haml
.new
  %h1 Edit #{@eval[:title]}
  = render "form"

app/views/evals/index.html.haml
.new
  .avatar-name-container
    %h1 Evaluations
  - if can? :create, @eval
    .exit-container-plus
      = link_to new_eval_path do
        %i.icon-plus.tooltip-item
          .tooltip
            Create Evaluation
- if current_user.type == "Professor" && current_user.evals.empty?
  %p
    %i You do not appear to have any ongoing evaluations at the moment. How nice.
- else
  - if current_user.type == "Professor"   
    %table.table-minimal
      %thead
        %tr
          %th Title
          %th Created At
          %th Template Type
      %tbody
      - current_user.evals.each do |eval|
        %tr
          %td
            = link_to eval.title, eval_path(eval)
          %td #{eval.created_at.to_time.strftime('%B %e at %l:%M %p')}
          %td #{eval.template}

app/views/evals/new.html.haml
.new
  %h1 New Evaluation
  = render "form"

app/views/evals/show.html.haml
.new
  %h1 #{@eval[:title]}
  %p= link_to "Edit  ", edit_eval_path(@eval)
  %p= link_to "Delete", @eval, :confirm => 'Are you sure?', :method => :delete
  %p Template Type: #{@eval[:template]}
  %h1 Categories
  - @eval.categories.each do |category|
    %h6= category.title
    Total:
    = format_score(category.max_score)
    - category.comments.each do |comment|
      %li= comment.description
    %br