config/routes.rb
Rails.application.routes.draw do
  root 'user_sessions#new'

  resources :courses, only: [:new, :create, :show, :edit, :update, :destroy, :index], shallow: true do
    resources :rosters, only:[:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  resources :users, only: [:show, :edit, :update, :destroy, :new, :create] do
    member do
      get :activate
      patch :confirm
    end
  end

  resources :rosters do
    member do
      get :export
    end
  end

  resources :evals, shallow: true do
    resources :categories, only: [:new, :create, :edit, :update, :destroy], shallow: true do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :students, only: [:show] do
    resources :grades, only: [:new, :create, :show, :edit, :update ]
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.professor = current_user
    if @course.save
      redirect_to @course, notice: "#{@course.name} was created!"
    else
      flash.now[:alert] = "Your course was not saved..."
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      redirect_to @course, notice: "Change to #{@course.name} were successfully saved!"
    else
      flash.now[:alert] = "Changes to #{@course.name} were not saved..."
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
  end

    private

  def course_params
    params.require(:course).permit(:name, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_errors.html.haml
.error-messages
  %h4
    =pluralize(@course.errors.count, "error")
    prohibited this course from saving:

  %ul
    -errors.full_messages.each do |msg|
    %li= msg

app/views/courses/_course_form.html.haml
-if @course.errors.any?
  = render 'course_errors'
=form_for @course do |f|
  .user-input
    = f.label :name, "Course Name:"
    = f.text_field :name
  .user-input
    =f.label :description, "Course Description:"
    =f.text_area :description
  .submit-btn
    =f.button

app/views/courses/_section_tab_box.html.haml
.vertical-tabs-container
  .vertical-tabs
    - @course.rosters.each.with_index do |roster, index|
      - if index == 0
        =link_to roster.section_name, "#", class: "js-vertical-tab vertical-tab is-active", rel: "tab#{index}"
      - else
        =link_to roster.section_name, "#", class: "js-vertical-tab vertical-tab", rel: "tab#{index}"
  .vertical-tab-content-container
    - @course.rosters.each.with_index do |roster, index|
      - if index == 0
        =link_to roster.section_name, "#", class: "js-vertical-tab-accordion-heading vertical-tab-accordion-heading is-active", rel: "tab#{index}"
        .js-vertical-tab-content.vertical-tab-content{id: "tab#{index}"}
          %h2= link_to "#{roster.section_name}", roster_path(roster)
          %p=format_score(roster.average_score)


      - else
        =link_to roster.section_name, "#", class: "js-vertical-tab-accordion-heading vertical-tab-accordion-heading", rel: "tab#{index}"
        .js-vertical-tab-content.vertical-tab-content{id: "tab#{index}"}
          %h2= link_to "#{roster.section_name}", roster_path(roster)
          %p=format_score(roster.average_score)

app/views/courses/edit.html.haml
%h1
  Edit
  = @course.name
=render 'course_form'

app/views/courses/index.html.haml
.new
  .exit-container-plus
    = link_to new_course_path do
      %i.icon-plus.tooltip-item
        .tooltip
          Add a Course
  %h1 Courses
- if current_user.type == "Professor" && current_user.courses.empty?
  %p
    %i You do not appear to have any ongoing courses at the moment. How nice.
- else
  - if current_user.type == "Professor"
    %table.table-minimal
      %thead
        %tr
          %th Course Title
          %th Created At
      %tbody
      - current_user.courses.each do |course|
        %tr
          %td
            = link_to course.name, course_path(course)
          %td #{course.created_at.to_time.strftime('%B %e at %l:%M %p')}

app/views/courses/new.html.haml
.new
  %h1 Create A Course!
  = render 'course_form'

app/views/courses/show.html.haml
.new
  %h1= @course.name
  %p
    %strong Course Descriptions:
    = @course.description
  %p= link_to "Edit this course", edit_course_path(@course)
  %hr/
%h2 Sections
-if @course.rosters.empty?
  %p
    %i You don't have any sections for this course yet. #{link_to "Add one!", new_course_roster_path(@course)}
-else
  =render 'section_tab_box'
%h2 TA's
-if @course.assistants.empty?
  %p
    %i You don't have any Teaching Assistants for this course yet. #{link_to "Add one!", new_user_path(course_ids: @course.id)}
-else
  %small= link_to "Add TA", new_user_path(course_ids: @course.id)
= render @course.assistants

app/views/courses/show.js.erb
$('#roster-index').html("<%= j(render  @rosters) %>");